jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      name: "SBOM generation example job"
      script:
        - # Add commands to generate SBOM here
        - sbom_generation_command
        - # Other build steps
